import { useState } from "react"
import Button from "../components/Button"
import Modal from "../components/Modal"

export default function ModalPage() {
  const [isModalOpen, setIsModalOpen] = useState(false)
  function handleClick() {
    setIsModalOpen(true)
  }

  function handleClose() {
    setIsModalOpen(false)
  }

  const actionBar = (
    <div>
      <Button danger onClick={()=>window.alert("clicked the danger button")}>Delete</Button>
      <Button primary onClick={handleClose}>Accept and Close</Button>
    </div>
  )

  return (
    <div>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus commodo viverra maecenas accumsan. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Hendrerit gravida rutrum quisque non tellus. Nec ullamcorper sit amet risus nullam eget. Donec et odio pellentesque diam volutpat commodo sed egestas egestas. Non diam phasellus vestibulum lorem sed. Neque volutpat ac tincidunt vitae. Iaculis at erat pellentesque adipiscing commodo elit at. Tortor aliquam nulla facilisi cras fermentum odio eu. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Vitae auctor eu augue ut lectus arcu bibendum at. Mattis enim ut tellus elementum.

Et pharetra pharetra massa massa ultricies mi quis hendrerit. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. Ut pharetra sit amet aliquam id diam. In iaculis nunc sed augue lacus viverra vitae congue. Sit amet est placerat in egestas erat imperdiet sed euismod. In eu mi bibendum neque. Non sodales neque sodales ut etiam sit. Diam phasellus vestibulum lorem sed risus. Tincidunt arcu non sodales neque sodales ut etiam. Vitae purus faucibus ornare suspendisse sed nisi lacus. Commodo elit at imperdiet dui. Eu nisl nunc mi ipsum faucibus vitae aliquet. Sagittis aliquam malesuada bibendum arcu vitae elementum. Dolor sit amet consectetur adipiscing elit ut. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus.

Et ligula ullamcorper malesuada proin libero nunc consequat interdum. Quam vulputate dignissim suspendisse in est ante. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Quam pellentesque nec nam aliquam. Sit amet volutpat consequat mauris nunc. Sagittis purus sit amet volutpat consequat mauris nunc congue. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Et molestie ac feugiat sed lectus vestibulum mattis. Neque aliquam vestibulum morbi blandit cursus risus. Eget magna fermentum iaculis eu non diam phasellus. Ipsum suspendisse ultrices gravida dictum fusce ut placerat. Sem integer vitae justo eget magna fermentum iaculis eu. Commodo viverra maecenas accumsan lacus vel facilisis. Mi quis hendrerit dolor magna eget est. Eget arcu dictum varius duis. Elementum nibh tellus molestie nunc non blandit massa. Ut morbi tincidunt augue interdum. At elementum eu facilisis sed odio. Morbi tristique senectus et netus et malesuada.

Volutpat commodo sed egestas egestas. Tincidunt ornare massa eget egestas purus viverra accumsan in nisl. Velit dignissim sodales ut eu. Facilisis volutpat est velit egestas dui id. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Nulla facilisi etiam dignissim diam quis enim. Purus non enim praesent elementum facilisis leo vel. Pellentesque elit eget gravida cum sociis natoque penatibus et. Fames ac turpis egestas integer eget. Nibh nisl condimentum id venenatis a condimentum. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Est ante in nibh mauris cursus. Mattis aliquam faucibus purus in. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus.

Orci eu lobortis elementum nibh tellus. Nunc mi ipsum faucibus vitae aliquet. Tincidunt augue interdum velit euismod. Ultricies mi quis hendrerit dolor magna eget est lorem. Accumsan sit amet nulla facilisi morbi. Dolor sit amet consectetur adipiscing elit ut aliquam. Tellus in hac habitasse platea dictumst vestibulum. Aliquam sem fringilla ut morbi tincidunt augue. Nisl purus in mollis nunc sed id semper. Habitant morbi tristique senectus et netus et malesuada fames. Id diam vel quam elementum pulvinar. Id ornare arcu odio ut. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Amet nisl suscipit adipiscing bibendum est ultricies integer. Ut porttitor leo a diam sollicitudin tempor id. Praesent elementum facilisis leo vel fringilla est ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing.

Volutpat lacus laoreet non curabitur gravida arcu ac. Posuere ac ut consequat semper viverra nam libero. Convallis convallis tellus id interdum velit laoreet id donec. Amet mauris commodo quis imperdiet massa tincidunt. Volutpat ac tincidunt vitae semper quis lectus nulla. Aliquet eget sit amet tellus cras. Eget nunc scelerisque viverra mauris in. Elementum nibh tellus molestie nunc non blandit massa enim. Sed faucibus turpis in eu mi bibendum neque egestas congue. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper. Enim nunc faucibus a pellentesque sit. Ornare massa eget egestas purus viverra accumsan in nisl nisi. Morbi non arcu risus quis varius quam quisque id diam. Commodo elit at imperdiet dui accumsan. Sed felis eget velit aliquet sagittis. Sed blandit libero volutpat sed cras. Ridiculus mus mauris vitae ultricies leo integer. Volutpat ac tincidunt vitae semper quis lectus. Ullamcorper morbi tincidunt ornare massa. Nibh sit amet commodo nulla facilisi nullam.

Mi sit amet mauris commodo quis imperdiet. Urna condimentum mattis pellentesque id nibh tortor. Turpis nunc eget lorem dolor sed viverra ipsum. In metus vulputate eu scelerisque felis imperdiet proin. Semper eget duis at tellus at urna. Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Suspendisse sed nisi lacus sed. Ut porttitor leo a diam sollicitudin tempor id eu. Bibendum neque egestas congue quisque egestas diam in. Viverra vitae congue eu consequat ac. Velit ut tortor pretium viverra suspendisse potenti nullam. Vivamus at augue eget arcu dictum varius. Sagittis orci a scelerisque purus. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Enim blandit volutpat maecenas volutpat blandit. Adipiscing vitae proin sagittis nisl. Morbi tristique senectus et netus et malesuada fames ac turpis.

Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Massa tempor nec feugiat nisl pretium fusce id velit. Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Aliquam ultrices sagittis orci a. Morbi tincidunt augue interdum velit. Eu consequat ac felis donec et odio. Ipsum dolor sit amet consectetur adipiscing elit duis tristique. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Elementum curabitur vitae nunc sed velit. Purus gravida quis blandit turpis cursus in. Auctor neque vitae tempus quam pellentesque nec nam aliquam. Sem fringilla ut morbi tincidunt augue interdum velit. Tortor consequat id porta nibh. Lacus laoreet non curabitur gravida arcu ac.

Est ante in nibh mauris cursus mattis. Quis ipsum suspendisse ultrices gravida dictum fusce. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Suscipit tellus mauris a diam maecenas sed enim ut sem. Ut etiam sit amet nisl. Pharetra diam sit amet nisl suscipit. Accumsan tortor posuere ac ut. Nibh tellus molestie nunc non blandit massa. Id porta nibh venenatis cras sed felis. Aliquam faucibus purus in massa tempor. Mattis nunc sed blandit libero volutpat sed cras. Eget dolor morbi non arcu risus. Consequat semper viverra nam libero justo laoreet. Quis varius quam quisque id diam vel quam elementum pulvinar. Id aliquet lectus proin nibh nisl condimentum.

Id nibh tortor id aliquet lectus proin nibh nisl. Sit amet mauris commodo quis imperdiet. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Mauris vitae ultricies leo integer malesuada. Rhoncus dolor purus non enim praesent elementum facilisis leo. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Quis varius quam quisque id diam vel quam. Facilisis magna etiam tempor orci. Nec ultrices dui sapien eget. Orci dapibus ultrices in iaculis. Mauris rhoncus aenean vel elit scelerisque. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Enim nulla aliquet porttitor lacus luctus accumsan. Amet nulla facilisi morbi tempus iaculis urna id. Tincidunt ornare massa eget egestas purus. Diam maecenas sed enim ut sem viverra aliquet. Tempor id eu nisl nunc mi ipsum. Dignissim enim sit amet venenatis urna cursus eget.

Sed ullamcorper morbi tincidunt ornare massa eget egestas. Eu sem integer vitae justo. In fermentum et sollicitudin ac orci. Dignissim sodales ut eu sem integer vitae. Nec nam aliquam sem et tortor. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Et odio pellentesque diam volutpat commodo sed. Egestas dui id ornare arcu odio ut sem nulla. Faucibus ornare suspendisse sed nisi lacus sed viverra. Mattis enim ut tellus elementum sagittis vitae et leo. Tortor dignissim convallis aenean et tortor at. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Nec nam aliquam sem et tortor consequat id. Scelerisque in dictum non consectetur a erat nam at lectus.

Bibendum est ultricies integer quis. Est ullamcorper eget nulla facilisi. Ultricies lacus sed turpis tincidunt id. Cursus sit amet dictum sit amet justo donec enim. Senectus et netus et malesuada fames ac. Vitae justo eget magna fermentum. Vitae turpis massa sed elementum tempus egestas sed sed risus. Risus pretium quam vulputate dignissim suspendisse in est ante. Et leo duis ut diam quam. Tincidunt arcu non sodales neque sodales ut. Mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id consectetur purus ut. Rhoncus mattis rhoncus urna neque viverra justo nec. Eget dolor morbi non arcu risus. Neque laoreet suspendisse interdum consectetur libero id. Mauris in aliquam sem fringilla ut morbi.

Leo in vitae turpis massa sed elementum tempus egestas sed. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Risus viverra adipiscing at in. Dolor purus non enim praesent elementum facilisis leo vel fringilla. Tincidunt ornare massa eget egestas purus viverra accumsan in nisl. Ac auctor augue mauris augue neque gravida in fermentum et. Ut consequat semper viverra nam libero. Arcu non sodales neque sodales ut. Eleifend quam adipiscing vitae proin sagittis. Enim sed faucibus turpis in eu mi bibendum neque egestas.

Malesuada nunc vel risus commodo. Ac ut consequat semper viverra nam libero justo laoreet. Risus at ultrices mi tempus imperdiet nulla. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Cursus mattis molestie a iaculis at erat. Eget nunc scelerisque viverra mauris in aliquam sem fringilla. Nulla pharetra diam sit amet. Est pellentesque elit ullamcorper dignissim. Tincidunt arcu non sodales neque sodales ut. Bibendum arcu vitae elementum curabitur vitae nunc. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu.

In fermentum et sollicitudin ac orci phasellus. Nullam non nisi est sit amet facilisis. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Platea dictumst vestibulum rhoncus est. Blandit massa enim nec dui nunc mattis enim ut. A diam sollicitudin tempor id. Turpis cursus in hac habitasse platea dictumst quisque sagittis. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Orci porta non pulvinar neque. Sit amet mauris commodo quis imperdiet massa. Aliquet bibendum enim facilisis gravida neque convallis. Sit amet luctus venenatis lectus. Aliquam faucibus purus in massa tempor nec feugiat nisl pretium.

Habitant morbi tristique senectus et netus et malesuada fames ac. Donec ac odio tempor orci dapibus ultrices in iaculis. Nulla pellentesque dignissim enim sit amet venenatis urna. Fermentum odio eu feugiat pretium nibh ipsum. Condimentum mattis pellentesque id nibh tortor id aliquet. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Convallis aenean et tortor at. Sodales ut eu sem integer vitae justo eget magna fermentum. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. Consectetur libero id faucibus nisl tincidunt. In nibh mauris cursus mattis molestie a. Elit pellentesque habitant morbi tristique. Ridiculus mus mauris vitae ultricies. Sit amet est placerat in egestas erat. Diam phasellus vestibulum lorem sed. Commodo odio aenean sed adipiscing diam donec adipiscing. Purus viverra accumsan in nisl. Dui vivamus arcu felis bibendum.

Nunc aliquet bibendum enim facilisis gravida neque. Pretium lectus quam id leo in vitae turpis massa. Arcu non odio euismod lacinia at quis risus. Id diam vel quam elementum pulvinar. Nisi vitae suscipit tellus mauris a. Maecenas sed enim ut sem viverra aliquet eget sit amet. Maecenas ultricies mi eget mauris pharetra. Facilisi cras fermentum odio eu. Ipsum suspendisse ultrices gravida dictum fusce. In ornare quam viverra orci sagittis eu volutpat. Ac feugiat sed lectus vestibulum mattis ullamcorper. Interdum velit laoreet id donec. Diam in arcu cursus euismod quis. Praesent tristique magna sit amet purus. Et tortor at risus viverra adipiscing at. Vitae sapien pellentesque habitant morbi. Aliquam ut porttitor leo a.

Consectetur lorem donec massa sapien faucibus et molestie ac. Adipiscing at in tellus integer feugiat scelerisque. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Id diam maecenas ultricies mi eget mauris pharetra et ultrices. Aliquet nibh praesent tristique magna sit amet purus gravida. Amet facilisis magna etiam tempor orci. A condimentum vitae sapien pellentesque habitant morbi tristique. Id cursus metus aliquam eleifend mi in nulla. Bibendum at varius vel pharetra. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Venenatis lectus magna fringilla urna porttitor rhoncus. Volutpat blandit aliquam etiam erat velit scelerisque in. Vulputate odio ut enim blandit volutpat maecenas volutpat. Semper quis lectus nulla at volutpat. Tristique magna sit amet purus gravida quis blandit. Eget nullam non nisi est sit amet.

Suspendisse ultrices gravida dictum fusce ut placerat orci. Odio ut sem nulla pharetra diam sit amet nisl. Dolor magna eget est lorem ipsum. Ipsum consequat nisl vel pretium lectus quam. Quis varius quam quisque id diam vel. Vel facilisis volutpat est velit. Massa placerat duis ultricies lacus. Dignissim suspendisse in est ante in. Ac placerat vestibulum lectus mauris ultrices eros in. Et egestas quis ipsum suspendisse ultrices gravida. Tortor id aliquet lectus proin nibh. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque in.

Mus mauris vitae ultricies leo. Enim ut sem viverra aliquet eget sit amet. Nunc congue nisi vitae suscipit. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Justo laoreet sit amet cursus sit amet dictum. Malesuada fames ac turpis egestas integer eget aliquet nibh. Leo in vitae turpis massa sed elementum tempus egestas. Viverra suspendisse potenti nullam ac. Dui id ornare arcu odio. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Proin sed libero enim sed faucibus turpis in. Massa sed elementum tempus egestas.
      <Button success outline onClick={handleClick}>
        Open Modal
      </Button>
      {isModalOpen && <Modal onClose={handleClose} actionBar={actionBar}>Content</Modal>}
    </div>
  )
}
